# Generated by Django 5.0.6 on 2024-06-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_flower_choise'),
    ]

    operations = [
        migrations.AddField(
            model_name='autorsbucket',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='busket',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compositions',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flower',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='flower',
            name='choise',
            field=models.CharField(choices=[('Compositions', 'Compositions'), ('Busket', 'Busket'), ('AutorsBucket', 'AutorsBucket')], max_length=100),
        ),
    ]
