# Generated by Django 5.0.6 on 2024-06-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_autorsbucket_photo_url_busket_photo_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autorsbucket',
            name='flowers',
            field=models.ManyToManyField(blank=True, related_name='autors_buckets', to='main.flower'),
        ),
        migrations.AddField(
            model_name='busket',
            name='flowers',
            field=models.ManyToManyField(blank=True, related_name='baskets', to='main.flower'),
        ),
        migrations.AddField(
            model_name='compositions',
            name='flowers',
            field=models.ManyToManyField(blank=True, related_name='compositions', to='main.flower'),
        ),
        migrations.AlterField(
            model_name='flower',
            name='choise',
            field=models.CharField(choices=[('AutorsBucket', 'AutorsBucket'), ('Compositions', 'Compositions'), ('Busket', 'Busket')], max_length=100),
        ),
    ]
