# Generated by Django 5.0.6 on 2024-06-07 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_autorsbucket_flowers_busket_flowers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autorsbucket',
            name='photo_url',
            field=models.CharField(default='', max_length=9999),
        ),
    ]
