# Generated by Django 5.0.6 on 2024-06-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_autorsbucket_photo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autorsbucket',
            name='photo_url',
        ),
        migrations.RemoveField(
            model_name='busket',
            name='photo_url',
        ),
        migrations.RemoveField(
            model_name='compositions',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='autorsbucket',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='busket',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='compositions',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos', verbose_name='Фото'),
        ),
    ]
